# Generated by Django 6.0.5 on 2026-06-05 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_post_publish_alter_post_slug_alter_post_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2026, 6, 5, 14, 30, 58, 401735, tzinfo=datetime.timezone.utc)),
        ),
    ]
